### ISSUE TITLE
#1 Do Pre-EDA

### ISSUE THREAD

**Issue by FrediThs** [xEgle/ds-ml-project-kickstarter#13]
As data scientist I want to know how good my data is overall and what columns make sense

**Acceptance criteria:** 
- it is known and understood why and if we have duplicates
- it is known which columns are usable and which can be removed because they are redundant and/or contain to many nulls

**Comment by FrediThs** [comment]
**Conclusion from duplicates**
- We have duplicates: 26958/209221 = 0,1288
- they are caused by the arrays
- but we don't know what is important

**Comment by FrediThs** [comment]
Results for columns are available in the data dictionary, will push the results tomorrow

**Comment by Pipwidgeon** [comment]
Fredi took care ✅
