### ISSUE TITLE
#1 Data cleaning to dos

### ISSUE THREAD

**Issue by FrediThs** [xEgle/ds-ml-project-kickstarter#16]
Renaming items: ✅ Philippa and Egle took care
-- blurp = description
-- category items: 
-- id of category = id_category
-- name of category = category
-- slug of category = category_sub
- from creator items: 
-- keep id and rename to id_creator
-- drop rest from here > gdpr
- from location items: 
-- keep name as city (e.g.Pittsford), state (e.g. "VT")
-- drop rest

Date columns: ✅ Philippa took care
- add prefix date_* to launched_at, created_at, deadline, state_changed_at so that they can be sorted better
- is date changed at the same as deadline? if yes: drop, if not: keep

Currency issues: ✅ Philippa took care
- confirm how many cases we have where the currency != to current_currency 
- check pledged amounts for validity > we don't know which currency conversion correct
-- drop columns that are wrong
-- if no longer needed: drop currency conversion column
- create goal in converted USD and rename goal to goal_original_currency

Spotlight should be dropped after EDA because of data leakage (is set only for successful campaigns)

**Won't do:** 
Photo: 
- create dummy that indicates if someone has a picture or not
-  drop rest

Profile: 
- create dummy that indicates if a Link exists or not
- drop existing column

**Comment by Pipwidgeon** [comment]
In progress:
Renaming items:
-- blurp = description

Date columns:

    add prefix date_* to launched_at, created_at, deadline, state_changed_at so that they can be sorted better
    is date changed at the same as deadline? if yes: drop, if not: keep
