### ISSUE TITLE
#1 EDA

### ISSUE THREAD

**Issue by xEgle** [xEgle/ds-ml-project-kickstarter#2]
As DS I want to have an overview on my data so that I can develop a model 

**Acceptance criteria**
- Understand project status > in particular: 
- - check if we can use open items
- - What does 'active' mean? 
- - Can it contain pledges that already reached their funding goal but have not yet reached the deadline?
- Create correlation matrix / heatmap of features
- - identify useless features
- Understand distribution and outliers / boxplotting
- - define which outliers need to be taken care of

**Comment by FrediThs** [comment]
Ideas for useful graphs: 
- Success/Failure probability by the main category
