### ISSUE TITLE
#1  Goal setting

### ISSUE THREAD

**Issue by FrediThs** [xEgle/ds-ml-project-kickstarter#9]
As user I want to have goals for my project, so that I can create follow up tickets.

**Acceptance criteria:** 
- goal is set

**Result:** 
General goals: 
- provide generals insights in the data: 
-- what type of campaigns 
-- what factors drive success - what are their chances of success?
-- assess whether or not Kickstarter is a good funding option for them (categories of funding),
- create ML model that predicts wether or not a campaign is successful 

Assumptions: 
- our stakeholder is Kickstarter itself
- their goal is to guide users better > have more successful funding, avoid customers that will not have success

Next steps: 
- find out how to access the tables: python ✅ > Code snippet by @xEgle 
- SPIKE (HL): understand what kickstarter sees as the "success of a campaign". Suggestion: check goal - actual amount of campaign
- SPIKE (FT): understand how tables work: are they daily snapshots? 
- SPIKE (PS): data dict to know what the table columns mean 
- SPIKE (EW): find out what needs transformation and how to do it > extract items from dict,  convert unix time

**Comment by henryklange** [comment]
- Unix time conversion push
- readme file 
- which columns are useful to use (data dictionary)
